Repository betagouv/anssi-recommandations-cyber, pull requests merged in 2025-10, with the labels that each got.

#38 Ajout des assets qu'on avait oublié
  ui/public/fonts/Marianne-Bold.woff
  ui/public/fonts/Marianne-Bold.woff2
  ui/public/fonts/Marianne-Bold_Italic.woff
  ui/public/fonts/Marianne-Bold_Italic.woff2
  ui/public/fonts/Marianne-ExtraBold.woff
  ui/public/fonts/Marianne-ExtraBold.woff2
  ui/public/fonts/Marianne-Light.woff
  ui/public/fonts/Marianne-Light.woff2
  ui/public/fonts/Marianne-Light_Italic.woff
  ui/public/fonts/Marianne-Light_Italic.woff2
  ui/public/fonts/Marianne-Medium.woff
  ui/public/fonts/Marianne-Medium.woff2
  ui/public/fonts/Marianne-Medium_Italic.woff
  ui/public/fonts/Marianne-Medium_Italic.woff2
  ui/public/fonts/Marianne-Regular.woff
  ui/public/fonts/Marianne-Regular.woff2
  ui/public/fonts/Marianne-Regular_Italic.woff
  ui/public/fonts/Marianne-Regular_Italic.woff2
  ui/public/icons/croix-fermeture.svg
  ui/public/icons/fleche-extension.svg
  ui/public/icons/information.svg
  ui/public/icons/lien-externe.svg
Labels: documentation

#41 Affiche le contenu "markdown" correctement
  ui/package-lock.json
  ui/package.json
  ui/src/App.svelte
Labels: enhancement

#42 [CI/CD] Ajoute un docker compose
  README.md
  docker-compose.yml
Labels: documentation, enhancement
